THEME_NAME: jekyll-klise
THEME_VERSION: 1.0.0
POSTS_PER_PAGINATION: 5

colors:
    light:
        background_body: "#ffffff"
        background_box: "#ffffff"
        background_contrast: "#ececec"
        text_content: "#434648"
        text_content_secondary: "#0d122b"
        tag:
            bg: "#f3f3f3"
            fg: "#000000"
    dark:
        background_body: "#0a0a0a"
        background_box: "#222222"
        background_contrast: "#666666"
        text_content: "#ffffff"
        text_content_secondary: "#ffffff"
        tag:
            bg: "#424242"
            fg: "#ffffff"

font:
    size: 16
    family: "Roboto, sans-serif"

line_height: 24

box:
    radius: 20
    shadow: "0 0 30px rgba(0,0,0,0.05)"

settings:
    loop:
        authors: true
        tags: true
        featured_image: true
    post:
        authors: true
        tags: true
        featured_image: true
    footer:
        feed_icon: true
